/**
 * Q-0001: Make agent registration one-command
 *
 * Usage:
 *   npm --workspace apps/agent run register
 *   npm --workspace apps/agent run register -- --dry-run
 *   npm --workspace apps/agent run register -- --show-key
 *   npm --workspace apps/agent run register -- --private-key 0x...
 *   npm --workspace apps/agent run register -- --rpc https://testrpc.xlayer.tech/terigon
 *   npm --workspace apps/agent run register -- --metadata-ipfs
 */

import { JsonRpcProvider, Wallet, formatEther, Contract } from "ethers";
import { randomBytes } from "node:crypto";
import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import {
  XLAYER_TESTNET,
  citizenRegistryAbi,
  createReadProvider
} from "@niuma/sdk";

// ── Deployment ──────────────────────────────────────────────────────

interface Deployment {
  chainId: number;
  contracts: Record<string, string>;
}

function loadDeployment(): Deployment | null {
  const candidates = [
    resolve(process.cwd(), "world", "deployments", "1952.json"),
    resolve(process.cwd(), "..", "..", "world", "deployments", "1952.json"),
  ];
  const filePath = candidates.find((c) => existsSync(c));
  if (!filePath) return null;
  return JSON.parse(readFileSync(filePath, "utf8"));
}

// ── State file ──────────────────────────────────────────────────────

const STATE_DIR = resolve(process.cwd(), ".niuma");
const STATE_FILE = resolve(STATE_DIR, "agent-state.json");

interface AgentState {
  wallet: string;
  citizenId: number | null;
  registeredAt: string | null;
  txHash: string | null;
}

function loadState(): AgentState | null {
  if (!existsSync(STATE_FILE)) return null;
  return JSON.parse(readFileSync(STATE_FILE, "utf8"));
}

function saveState(state: AgentState): void {
  mkdirSync(STATE_DIR, { recursive: true });
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2) + "\n");
}

// ── Env file for private key (never committed) ──────────────────────

const ENV_FILE = resolve(process.cwd(), ".env.agent");

function loadEnvKey(): string | null {
  if (!existsSync(ENV_FILE)) return null;
  const content = readFileSync(ENV_FILE, "utf8");
  const match = content.match(/^AGENT_PRIVATE_KEY\s*=\s*(0x[0-9a-fA-F]{64})\s*$/m);
  return match ? match[1] : null;
}

function saveEnvKey(privateKey: string, wallet: string): void {
  const lines = [
    "# Auto-generated by niuma agent register — DO NOT COMMIT",
    `AGENT_PRIVATE_KEY=${privateKey}`,
    `AGENT_WALLET=${wallet}`,
    "",
  ].join("\n");
  writeFileSync(ENV_FILE, lines);
}

// ── CLI arg parsing ─────────────────────────────────────────────────

function parseArgs(): {
  dryRun: boolean;
  showKey: boolean;
  privateKey: string | null;
  rpc: string;
  citizenRegistry: string | null;
  metadataURI: string;
} {
  const args = process.argv.slice(2);
  return {
    dryRun: args.includes("--dry-run"),
    showKey: args.includes("--show-key"),
    privateKey:
      args.findIndex((a) => a === "--private-key") >= 0
        ? args[args.findIndex((a) => a === "--private-key") + 1] ?? null
        : null,
    rpc:
      args.findIndex((a) => a === "--rpc") >= 0
        ? args[args.findIndex((a) => a === "--rpc") + 1] ?? XLAYER_TESTNET.rpcUrl
        : XLAYER_TESTNET.rpcUrl,
    citizenRegistry:
      args.findIndex((a) => a === "--citizen-registry") >= 0
        ? args[args.findIndex((a) => a === "--citizen-registry") + 1] ?? null
        : null,
    metadataURI: args.includes("--metadata-ipfs")
      ? `ipfs://agent-${Date.now()}`
      : `https://niuma.city/agent/${Date.now()}`,
  };
}

// ── Main ────────────────────────────────────────────────────────────

async function main() {
  const opts = parseArgs();

  console.log("\n🏛️  NIUMA CITY — Agent Registration\n");

  // 1. Resolve private key
  let privateKey = opts.privateKey || loadEnvKey();
  let isNew = false;

  if (!privateKey) {
    console.log("📦 Generating new wallet...");
    privateKey = "0x" + randomBytes(32).toString("hex");
    isNew = true;
  }

  const wallet = new Wallet(privateKey);
  const address = wallet.address;

  console.log(`🔑 Wallet: ${address}`);
  console.log(`🌐 Network: ${XLAYER_TESTNET.name} (chainId ${XLAYER_TESTNET.chainId})`);
  console.log(`📡 RPC: ${opts.rpc}`);

  if (opts.showKey) {
    console.log(`⚠️  Private key: ${privateKey}`);
    console.log("   Store this securely. It will NOT be shown again by default.");
  } else {
    console.log("   (Use --show-key to display private key)");
  }

  // 2. Check balance
  const provider = createReadProvider(opts.rpc);
  let balance: bigint;
  try {
    balance = await provider.getBalance(address);
    const okb = formatEther(balance);
    console.log(`💰 OKB balance: ${okb}`);

    if (balance === 0n && !opts.dryRun) {
      console.log("\n⚠️  Wallet has zero OKB. You need OKB for gas on X Layer Testnet.");
      console.log("   Get testnet OKB from the X Layer faucet, then re-run this command.");
      console.log("   Faucet: https://www.okx.com/web3/faucet");

      // Save state and key even on failure so the agent can retry
      if (isNew) {
        saveEnvKey(privateKey, address);
        console.log(`\n💾 Wallet saved to ${ENV_FILE} (gitignored)`);
      }
      saveState({ wallet: address, citizenId: null, registeredAt: null, txHash: null });
      console.log("\n   Re-run after funding: npm --workspace apps/agent run register\n");
      process.exit(1);
    }
  } catch (err) {
    console.log(`⚠️  Could not fetch balance: ${err instanceof Error ? err.message : err}`);
    console.log("   Continuing in case RPC is temporarily unavailable...");
    balance = -1n;
  }

  // 3. Resolve CitizenRegistry address
  const deployment = loadDeployment();
  const citizenRegistryAddr =
    opts.citizenRegistry ||
    deployment?.contracts?.CitizenRegistry ||
    process.env.CITIZEN_REGISTRY ||
    null;

  if (!citizenRegistryAddr) {
    console.log("\n❌ CitizenRegistry address not found.");
    console.log("   Provide it via --citizen-registry or set CITIZEN_REGISTRY env.");
    if (isNew) saveEnvKey(privateKey, address);
    process.exit(1);
  }

  console.log(`📜 CitizenRegistry: ${citizenRegistryAddr}`);

  // 4. Check if already registered
  const registry = new Contract(citizenRegistryAddr, citizenRegistryAbi, provider);
  let existingCitizenId = 0;
  try {
    existingCitizenId = Number(await registry.citizenOf(address));
  } catch {
    // citizenOf may revert for unregistered addresses
  }

  if (existingCitizenId > 0) {
    console.log(`\n✅ Already registered as Citizen #${existingCitizenId}`);
    saveState({ wallet: address, citizenId: existingCitizenId, registeredAt: new Date().toISOString(), txHash: null });
    console.log("   No transaction needed.\n");
    return;
  }

  // 5. Dry-run mode
  if (opts.dryRun) {
    console.log("\n🏃 Dry-run mode — no transaction will be sent.");
    console.log(`   Would call: CitizenRegistry.registerCitizen(${address}, "${opts.metadataURI}")`);
    console.log(`   Estimated gas: ~100000 OKB`);
    if (isNew) {
      saveEnvKey(privateKey, address);
      console.log(`\n💾 Wallet saved to ${ENV_FILE}`);
    }
    saveState({ wallet: address, citizenId: null, registeredAt: null, txHash: null });
    console.log("\n   Remove --dry-run to send the transaction.\n");
    return;
  }

  // 6. Send registration transaction
  console.log("\n🚀 Sending registration transaction...");
  const signer = wallet.connect(provider);
  const registryWithSigner = new Contract(citizenRegistryAddr, citizenRegistryAbi, signer);

  try {
    const tx = await registryWithSigner.registerCitizen(address, opts.metadataURI);
    console.log(`   tx hash: ${tx.hash}`);
    console.log("   Waiting for confirmation...");

    const receipt = await tx.wait();
    const citizenId = receipt.logs.length > 0 ? "see chain" : "pending";

    console.log(`\n✅ Registration confirmed in block ${receipt.blockNumber}`);
    console.log(`   Gas used: ${receipt.gasUsed.toString()}`);
    console.log(`   Citizen ID: check with CitizenRegistry.citizenOf(${address})`);

    // Read citizen ID from chain after confirmation
    let finalCitizenId: number | null = null;
    try {
      finalCitizenId = Number(await registry.citizenOf(address));
      console.log(`   🪪 Your Citizen ID: #${finalCitizenId}`);
    } catch {
      console.log("   (Citizen ID not yet indexed, check again shortly)");
    }

    saveState({
      wallet: address,
      citizenId: finalCitizenId,
      registeredAt: new Date().toISOString(),
      txHash: tx.hash,
    });

    if (isNew) {
      saveEnvKey(privateKey, address);
      console.log(`\n💾 Wallet saved to ${ENV_FILE}`);
    }

    console.log("\n🎉 Welcome to NIUMA CITY!");
    console.log("   Next: pick a quest from npm --workspace apps/agent run bootstrap\n");
  } catch (err) {
    console.log(`\n❌ Transaction failed: ${err instanceof Error ? err.message : err}`);
    if (isNew) saveEnvKey(privateKey, address);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
